### ISSUE TITLE
SQLDroidDatabaseMetaData/getColumns nullable handling bug

### ISSUE THREAD

**Issue by fefrain** [SQLDroid/SQLDroid#17]
I think that lines 227 and following in SQLDroidDatabaseMetaData contain a keystroke error:
They should be:

if ( nullable == 0 ) {
    column[10] = new Integer(1);
}
else if ( nullable == 1 ) {
    column[10] = new Integer(0);
}

instead of new Integer[X].
Thanks.

**Comment by jhannes** [comment]
Fixed in f99a66adbcccaeba9e902bb953edcc64a0ef0640
