### ISSUE TITLE
SQLiteDatabase/changedRowCount: maybe we can use "select changes()" to get the count of changed rows

### ISSUE THREAD

**Issue by GuguAbrams** [SQLDroid/SQLDroid#20]
Thanks for your great job.

I've recently found the CHANGES() pragma available inside of SQLite. So I'm adding some code:

SQLiteStatement stmt = sqliteDatabase.compileStatement("SELECT CHANGES()");
 long cnt = stmt.simpleQueryForLong();
 stmt.close();
 return (int)cnt;

:D

**Comment by dperiwal** [comment]
Thanks. Fixed with #65.
