### ISSUE TITLE
SQLDroid connection pooling issue

### ISSUE THREAD

**Issue by femski** [SQLDroid/SQLDroid#23]
I am getting random errors like below (attempt to reopen closed connection etc).

It seems SQLDroid keeps track of open connections and closes the underlying database when no connections are left open. But it seems to close live connections sometimes - I am not sure how.

When I do getConnection and close on a connection - I assume no one else can close these connections before I close it. But it seems SQLDroid does close the connection in the background. How do I stop this ?

```
11-01 19:52:13.523: E/MetarMap(26622): java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /storage/sdcard0/Android/data/com.metarmap.tab/files/databases/prefs.sqlite
11-01 19:52:13.523: E/MetarMap(26622):     at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
11-01 19:52:13.523: E/MetarMap(26622):     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1310)
11-01 19:52:13.523: E/MetarMap(26622):     at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1253)
11-01 19:52:13.523: E/MetarMap(26622):     at org.sqldroid.SQLiteDatabase.rawQuery(SQLiteDatabase.java:116)
11-01 19:52:13.523: E/MetarMap(26622):     at org.sqldroid.SQLDroidPreparedStatement.executeQuery(SQLDroidPreparedStatement.java:212)
```

**Comment by camueller** [comment]
This should be fixed by my pull request https://github.com/SQLDroid/SQLDroid/commit/4666757512f8019ad1f11eed3c5d5c16c7bb7297

**Comment by dperiwal** [comment]
The pull request 4666757 looks good to me.
