### ISSUE TITLE
Make setAutoCommit() method implementation safe.

### ISSUE THREAD

**Issue by dperiwal** [SQLDroid/SQLDroid#29]
In the class SQLDroidConnection, modify the setAutoCommit() method to invoke endTransaction() only after checking that the current thread has a transaction pending in the database.  This is to avoid some intermittent 'database locked' behavior observed from the android.database.sqlite.SQLiteDatabase class in some versions of Android SDK. I don't have a reproducible use case but the change should make the code safe anyway.

**Comment by donv** [comment]
@dperiwal This is done, right?

**Comment by dperiwal** [comment]
Yes @donv , This is fixed. Thanks.
