### ISSUE TITLE
Getting incorrect timestamps after 12:00 noon

### ISSUE THREAD

**Issue by tschoenbachler** [SQLDroid/SQLDroid#33]
Traced to the following code segment - we modified the hh to HH in the simple date formatter and all is well. 

  public Timestamp getTimestamp(int index) throws SQLException {
    try {
      ResultSetMetaData md = getMetaData();
      Timestamp timestamp = null;
      switch ( md.getColumnType(index)) {
        case Types.INTEGER:
        case Types.BIGINT:
          timestamp = new Timestamp(getLong(index));
          break;
        case Types.DATE:
          timestamp = new Timestamp(getDate(index).getTime());
          break;
        default:
          // format 2011-07-11 11:36:30.0
          try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss.S");
            java.util.Date parsedDate = dateFormat.parse(getString(index));
            timestamp = new Timestamp(parsedDate.getTime());
          } catch ( Exception any ) {
            any.printStackTrace();
          }
          break;

      }
      return timestamp;
    } catch (android.database.SQLException e) {
      throw SQLDroidConnection.chainException(e);
    }
  }

**Comment by zac1608** [comment]
eg. timestamp 2015-08-29 12:35:31 getHours() returns 0, also getTimeStamp sets hours to 0.

**Comment by donv** [comment]
Hi @zac1608 and @tschoenbachler !

I am busy with other projects.  Can you do a pull request?

**Comment by zac1608** [comment]
@donv, I'll do that as soon as I prepare good patch for it. Workaround is for app level :)

**Comment by zac1608** [comment]
I can confirm that changing SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss.S"); to SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S"); fixes problem (hh -> HH).

**Comment by donv** [comment]
Cool!

**Comment by ergouser** [comment]
If I'm reading this document, https://www.sqlite.org/datatype3.html correctly, it describes the data and time format at: 

TEXT as ISO8601 strings ("YYYY-MM-DD HH:MM:SS.SSS").

so the format would appear to be 

"yyyy-MM-dd HH:mm:ss.SSS"

That is, the centiseconds and milliseconds should not be dropped.

Issue #37 seems to be caught on both of these problems.

Pragmatically, it might be worth making the SimpleDateFormat a public static (or protected with a getter/setter/whatever) in the SQLDroidResultSet - a little flexibility in date formatting, even if not strictly standard compliant, might not be a bad thing.

**Comment by jhannes** [comment]
@ergouser Sounds like a good idea, but be aware that SimpleDateFormat is surprisingly not thread-safe.

**Comment by ergouser** [comment]
good point, but that's a fairly small area of code to synchronize.  I'm trying to remember if the formatter is forgiving of missing milliseconds.  That is, will "yyyy-MM-dd HH:mm:ss.SSS" parse 2015-08-29 12:35:31?  It seemed to with the tenths (.S) so there may not be an issue with just adding the milliseconds.

**Comment by ergouser** [comment]
The format could also be a static String rather than the formatter.  A DateFormat has more flexibility but that's probably not required.

**Comment by jhannes** [comment]
@ergouser I agree. I've extracted the format String as a constant and added .SSS, which seems to work.

I found that .S also works, but trying the same with JodaTime (in another context), .SSS is required. I think SimpleDateFormat is more lenient. I think .SSS is probably best. I've changed to this in my commit.
