### ISSUE TITLE
ResultSet.getObject("columnName") returns value from preceding column

### ISSUE THREAD

**Issue by axelfontaine** [SQLDroid/SQLDroid#36]
This is an off by one with the index somewhere. It is causing me all kinds of classcastexceptions as the types don't match. getInt() or getString() are not affected.

This is a biggie, as it will lead to data corruption for sure.

**Comment by jhannes** [comment]
Fixed in 85807d55003c40654957c1e6d73fa3229a681c58 (which predates the bug, but was probably not released)

The new unit tests prove that it's working: https://github.com/SQLDroid/SQLDroid/blob/master/src/test/java/org/sqldroid/SQLDroidTest.java#L92
