### ISSUE TITLE
Database with ?timeout=xxx param carries that param on the filename

### ISSUE THREAD

**Issue by rotter** [SQLDroid/SQLDroid#43]
I tried to use the timeout param, but the database file gets created with the "?timeout=xx" param on the filename, which I dont think is the expected behavior.

This caused a lot of problems in my code, as my code to delete the file would file because I tried to delete the raw filename, without the "?timeout" part. I had to use a rooted device to find out the problem.

And "?" is usually a filename wildcard (not sure if also on Linux), I don't even know how it accepted the file creation.

**Comment by jhannes** [comment]
This was fixed in 0c172f0e98f0304e9d173219d73e822d6c05c066
