### ISSUE TITLE
Add test suite

### ISSUE THREAD

**Issue by donv** [SQLDroid/SQLDroid#5]
@dperiwal @ergouser @kristianlm @SQLDroid @SQLDroid/developers 

Addressing each of you in case you are not watching the repository :)

Before releasing the 1.0.0 version, I think we should have a working test suite.

I experienced a regression between version 0.3.0 and 1.0.0.RC1, and we really should avoid that.

I can add a test suite using Ruboto.  I am on the Ruboto team, and that is how I use SQLDroid, so that is the natural way for me to test it.  Does anybody else want to add a test suite in another way?  Please speak up!  I will back up any effort on this.

If we decide that adding a test suite using Ruboto is OK, I would like some input on how to organise the test project.  The easiest way for me is to convert the project to a Ruboto project.  That will pollute the project a little, but makes testing very easy.  I will push a proposal on how to do this on a "ruboto" branch so you can see how I imagine we can do it.  Again, I welcome input on other ways to do it, for example as a separate test project independent of the core project.

When a test suite is in place, we will run it on a continuos integration server on every commit to avoid regressions.

What do you think?

**Comment by spyhunter99** [comment]
I'm doing some work over here to get everything rigged into maven. Can someone explain the build process and the "compat" src folder?

**Comment by spyhunter99** [comment]
quick update, i was able to get the test to run on device (android) but there's at least one failure

`
  statement = con.createStatement();
      hasResultSet = statement.execute("SELECT * FROM dummytable where name = 'fig'");  // no matching result
      assertFalse("Should not return a result set", hasResultSet);
`

once this is working i can open a PR

**Comment by spyhunter99** [comment]
after more testing i was able resolve a failing unit test related to empty vs null resultsets. however i still have 5 asserts that fail, all of them are related to update statements not returning the correct number of rows affected. any pointers?

**Comment by spyhunter99** [comment]
Found the root cause.
```
From SQLiteDatabase
The count of changed rows.  On JNA platforms, this is a call to sqlite3_changes
 On Android, it's a convoluted call to a package-private method (or, if that fails, the
response is '1'.
  public int changedRowCount
````

so the fix is to change the test to assert >= 1

**Comment by ergouser** [comment]
Do we know why/where this code fails?  If anyone would like to capture 
the exceptions we could take a look at why.  The return 1 is a complete 
fake - it will be returned even if the update failed.

Last change count is listed as still being in SQLiteDatabase.java

It may be that it was once static(???), in which case

           getChangedRowCount = 
sqliteDatabase.getClass().getDeclaredMethod("lastChangeCount", 
(Class<?>[])null);

goes to:

           getChangedRowCount = 
sqliteDatabase.getClass().getDeclaredMethod("lastChangeCount", 
(Class<?>[]){sqliteDatabase.getClass()});



   try {
           // Android
           getChangedRowCount = 
sqliteDatabase.getClass().getDeclaredMethod("lastChangeCount", 
(Class<?>[]){sqliteDatabase.getClass()});
           getChangedRowCount.setAccessible(true);
         } catch (Exception e) {
           // ignore
         }
       }
     }
     if ( getChangedRowCount != null ) {
       try {
         return ((Integer)getChangedRowCount.invoke(sqliteDatabase, 
(Object[])null)).intValue();
       } catch (Exception e) {
         // ignore
       }
     }


On 04/30/2016 05:15 PM, spyhunter99 wrote:
> |On JNA platforms, this is a call to sqlite3_changes|

-- 
Jim Redman
(505) 662 5156 x85
http://www.ergotech.com

**Comment by dperiwal** [comment]
I am trying to find a solution to the update count problem. I have a good idea of how to fix it. I am currently very busy with a new release of our product. I should be able to provide a solution and fix the related tests after middle of May.

**Comment by ergouser** [comment]
The code as is shouldn't be hopelessly broken although  I feel that 
there should be a better way than calling a package/private method.

On 05/01/2016 09:50 PM, dperiwal wrote:
>
> I am trying to find a solution to the update count problem. I have a 
> good idea of how to fix it. I am currently very busy with a new 
> release of our product. I should be able to provide a solution and fix 
> the related tests after middle of May.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/SQLDroid/SQLDroid/issues/5#issuecomment-216100790>
>

-- 
Jim Redman
(505) 662 5156 x85
http://www.ergotech.com

**Comment by dperiwal** [comment]
I have created a pull request <https://github.com/SQLDroid/SQLDroid/pull/65>
containing fixes for getting an update count and for getting a generated
row id. Thanks,

-- Damodar
