### ISSUE TITLE
Please setAutoCommit(true) after commit or rollback

### ISSUE THREAD

**Issue by jhannes** [SQLDroid/SQLDroid#54]
When running transactions in separate threads, the connections are not released. The result is that all but the first thread will get messages like this:

    02-24 10:29:24.614 13689-13724/XXXXX W/SQLiteConnectionPool: The connection pool for database '/data/data/XXXXX.db' has been unable to grant a connection to thread 323 (pool-1-thread-1) with flags 0x2 for 2430.154 seconds.
                                                                           Connections: 0 active, 1 idle, 0 available.

For example - running this in more than one thread will result in the lock:

        try (Connection connection = DriverManager.getConnection(jdbcUrl)) {
            connection.setAutoCommit(false);
            try (PreparedStatement stmt = connection.prepareStatement("insert into test_table (name) values (?)")) {
                stmt.setString(1, name);
                stmt.executeUpdate();
            }
            System.err.println("Wrote data to database");
            try (PreparedStatement stmt = connection.prepareStatement("select * from test_table")) {
                try (ResultSet rs = stmt.executeQuery()) {
                    while(rs.next()) {
                        System.err.println("Database row: " + rs.getString("name"));
                    }
                }
            }
            connection.commit();
            // Including the following will resolve the problem
            //connection.setAutoCommit(true);
        } catch (SQLException e) {
            throw rethrowUnchecked(e);
        }

Even though this probably was my fault, I think this should be changed in SQLDroid to avoid this headache (I spend several hours chasing down the problem)!

Thanks for a great library in SQLDroid!

**Comment by dperiwal** [comment]
As per JDBC standard, the default auto-commit mode for a database connection is true. So if you get a new connection, it's auto-commit mode should be true. However, once you have the connection and have explicitly set its auto-commit mode to false, it would not be appropriate for the JDBC driver to reset the auto-commit mode to true after each transaction commit because you may want to continue using the same connection with the auto-commit mode false for the next transaction.

**Comment by jhannes** [comment]
I see your point. But I haven't seen any other database that run into the same lock problem before and I expect others may run into the same headache. Isolating the the the problem was extremely time consuming. 

As an aside, I think the jdbc transaction model is very poorly designed.

**Comment by Dunemaster** [comment]
There is another issue with autocommit mode.
If autocommit is set to false, connections are not released from android sqllite connection pool even when the JDBC connection is properly closed. 

In logcat there are messages like this: 
**The connection pool for /data/data/dev.xx.xx/databases/XX has been closed but there are still 1 connections in use.  They will be closed as they are released back to the pool.

**Comment by jhannes** [comment]
Added test in 6ff177247b910e7b2f7a7449551dfbc6014e45dd
