### ISSUE TITLE
NullPointerException in SQLDroidResultSet.getTimestamp

### ISSUE THREAD

**Issue by jhannes** [SQLDroid/SQLDroid#56]
NullPointerException when doing getTimestamp on a null value.

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1035)
	at java.text.DateFormat.parse(DateFormat.java:577)
	at org.sqldroid.SQLDroidResultSet.getTimestamp(SQLDroidResultSet.java:543)

The code is currently:

            java.util.Date parsedDate = dateFormat.parse(getString(index));
            timestamp = new Timestamp(parsedDate.getTime());

This *should* work (not tested):

            String dateAsString = getString(index);
            if (dateAsString != null) {
                java.util.Date parsedDate = dateFormat.parse();
                timestamp = new Timestamp(parsedDate.getTime());
            }

**Comment by jhannes** [comment]
This is fixed by commit baf400c9e8be9941712095557c23f01784f1d691

**Comment by donv** [comment]
@jhannes Nice!  Did you get the invitation to join the project?

**Comment by jhannes** [comment]
@donv Invitation accepted. :-)

**Comment by donv** [comment]
Woohoo!
