### ISSUE TITLE
URL have to be "/data/data/PACKAGE_NAME_IN_DOT/DATABASE_NAME"

### ISSUE THREAD

**Issue by EmeraldWolfram** [SQLDroid/SQLDroid#66]
Thanks for the free JDBC driver, it works great until now for my project.

BUT

I found that the Quick Start Guide of this repository actually quite misleading.
I was a beginner in JAVA and I failed many times on getting the SQLiteCantOpenDatabaseException
because the path given in the example given was "jdbc:sqldroid:/com/example/myandroid/addressbook.db" but this actually didn't work for me.

After many hours of debugging, I finally get the reason which is due to the url for connection. 
(Sorry, I was a beginner in JAVA and Android. I normally do C only ^.^)

In order to work, the url format have to be in:
"jdbc:sqldroid:/data/data/PACKAGE_NAME_IN_DOT/DATABASE_NAME"
Example,
"jdbc:sqldroid:/data/data/com.info.ghiny.examsystem/invigilator.db"

Exception will be thrown without the "/data/data" in front
Exception will also be thrown if package name in "com/info/ghiny/examsystem" (in slash)
I don't really know why. 

Just a feedback for you that the Quick Start was not working.

However, nice work.

**Comment by jhannes** [comment]
Updated wiki and added a minimal example to README.md.

**Comment by donv** [comment]
@jhannes I am following you around setting labels and milestone for all the issues you work on and close.  Great work!

Can you set a fitting label and the "1.1" milestone for issues you work on or close?  That is even if the issue actually was fixed long ago.

I added the `Documentation` label for issues like this.

The `Support` label is a bucket label for all kinds of "Won't fix", "Not a bug", etc.  Anything where we help people, but don't actually change anything.
