### ISSUE TITLE
Create directory for databasefile if not exists

### ISSUE THREAD

**Issue by jhannes** [SQLDroid/SQLDroid#74]
Many support issues stem from the fact that you can only create a database file in an existing directory. Let's attempt to create the directory for the user.

**Comment by ergouser** [comment]
There's a boolean success/fail from mkdirs() - might be worth checking.  It would be nice to know why it failed, but that's not as easy to discover as you might hope.  II frequently put the db on /sdcard which fails if you don't have the correct permission.

**Comment by jhannes** [comment]
Actually, mkdirs returns false if the directory was already there. However, a check for directory.isDirectory afterwards will serve the same purpose. I'll add this.

I agree that it would be nice, but difficult, to know why it may not work.
