### ISSUE TITLE
Connection Problem

### ISSUE THREAD

**Issue by CaioPortugal** [SQLDroid/SQLDroid#9]
I've been trying to connect my database using your driver, but I have a problem ... I can load the driver but can't connect my database . I know how to use JDBC with Java , however it's too complicated connect android and my sqlite's database.  Many people have the same problem  ! Could you make a tutorial or video about " how to use SQLdroid step by step"?  , I didn't find on Youtube or other site

**Comment by jhannes** [comment]
Let's close this in favor of #74
